#!/usr/bin/env bash

host_name="$1"
stack_name="$2"
service_name="$3"
db_user="$4"
db_name="$5"

ssh -t "{$1}" "bin/dump-docker-db ${2} ${3} ${4} ${5}"

scp -3 -r "{host_name}":~/backup archilab-nas:~/
