#!/usr/bin/env bash

host_name="$1"
stack_name="$2"
service_name="$3"
db_user="$4"
db_name="$5"

ssh "${host_name}" "mkdir -p \${HOME}/bin"

scp "dump-docker-db" "${host_name}:\${HOME}/bin/"

ssh "${host_name}" "\${HOME}/bin/dump-docker-db" "${host_name}" "${stack_name}" "${service_name}" "${db_user}" "${db_name}"

ssh "archilab-nas" "mkdir -p \${HOME}/${host_name}"

scp -3 -r "${host_name}:\${HOME}/${host_name}/*" "archilab-nas:\${HOME}/${host_name}/"

ssh "${host_name}" "rm \${HOME}/${host_name}/*"
