#!/usr/bin/env bash

stack_name="$1"
service_name="$2"
db_user="$3"
db_name="$4"
instance_number=1
stack_service="${stack_name}_${service_name}"
stack_service_instance="${stack_service}.${instance_number}"
task_id="$(docker service ps ${stack_service} -q --no-trunc | head -n1)"
current_date="$(date +%Y-%m-%d)"

[ -d backup ] || mkdir backup

{
  docker exec "${stack_service_instance}.${task_id}" pg_dump -U "${db_user}" -c "${db_name}"
} > "backup/${service_name}_${current_date}.sql"
