#!/usr/bin/env bash

host_name="$1"
stack_name="$2"
service_name="$3"
db_user="$4"
db_name="$5"
backup_date="$6"

ssh "${host_name}" "mkdir \${HOME}/bin"

scp "restore-docker-db-dump" "${host_name}:\${HOME}/bin/"

ssh "archilab-nas" "mkdir -p \${HOME}/${host_name}"

scp -3 "archilab-nas:\${HOME}/${host_name}/${service_name}_${backup_date}.sql" "${host_name}:\${HOME}/${host_name}"

ssh "${host_name}" "\${HOME}/bin/restore-docker-db-dump" "${stack_name}" "${service_name}" "${db_user}" "${db_name}" "${backup_date}"

ssh "${host_name}" "rm \${HOME}/${host_name}/*"
