#!/usr/bin/env bash

stack_name="$1"
service_name="$2"
db_user="$3"
db_name="$4"
instance_number=1
stack_service="${stack_name}_${service_name}"
stack_service_instance="${stack_service}.${instance_number}"

task_id="$(docker service ps ${stack_service} -q --no-trunc | head -n1)"
{
  docker exec -i "${stack_service_instance}"."${task_id}" \
    psql -U "${db_user}" "${db_name}"
} < "${service_name}".sql
