#!/usr/bin/env bash

host_name="$1"
stack_name="$2"
service_name="$3"
db_user="$4"
db_name="$5"
backup_date="$6"

scp -3 archilab-nas:~/backup/"${service_name}_${backup_date}.sql" "${host_name}":~/backup/

ssh -t "${host_name}" \
    "restore-docker-db ${stack_name} ${service_name} ${db_user} ${db_name} ${backup_date}"

ssh -t "${host_name}" "rm ~/backup/*"
